services:
  social_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: social_api_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - .:/var/www
    networks:
      - social_network

  # 2. Nginx Web Server (Port 8082 used to avoid conflict)
  social_nginx:
    image: nginx:alpine
    container_name: social_api_nginx
    restart: unless-stopped
    ports:
      - "8082:80"
    volumes:
      - .:/var/www
      - ./docker/nginx:/etc/nginx/conf.d/
    networks:
      - social_network
    depends_on:
      - social_app

  # 3. MySQL Database Service (Port 33063 used to avoid conflict)
  social_db:
    image: mysql:8.0
    container_name: social_api_db
    restart: unless-stopped
    ports:
      - "33063:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - social_api_dbdata:/var/lib/mysql
    networks:
      - social_network

networks:
  social_network:
    driver: bridge

volumes:
  social_api_dbdata:
    driver: local